apiVersion: v1
data:
  acgNo: "34677"
  apiUrl: https://nks.apigw.ntruss.com
  basePath: /ncloud-api/v1
  clusterId: "2402"
  lbPublicSubnetNo: "0"
  lbSubnetNo: "32516"
  regionCode: KR
  regionNo: "1"
  vpcNo: "16392"
  zoneNo: "2"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"acgNo":"34677","apiUrl":"https://nks.apigw.ntruss.com","basePath":"/ncloud-api/v1","clusterId":"2402","lbPublicSubnetNo":"0","lbSubnetNo":"32516","regionCode":"KR","regionNo":"1","vpcNo":"16392","zoneNo":"2"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"ncloud-config","namespace":"kube-system"}}
  creationTimestamp: "2022-01-05T07:33:48Z"
  name: ncloud-config
  namespace: kube-system
  resourceVersion: "377"
  uid: 84277313-8871-4f8a-9307-c1a1ef435a6d
